spring:
  application:
    name: user-service
  profiles:
    active: dev
    
server:
  port: 8080
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

